apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-1-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: devops-project-1-app
  template:
    metadata:
      name: devops-project-1-pod
      labels:
        name: devops-project-1-app
    spec:
      containers:
      - name: devops-project-1-container
        image: beeeeeep/ci-pipeline:latest
        ports:
        - containerPort: 8080
