version: '3.8'

services:
  devops-project-app:
    image: beeeeeep/ci-pipeline:latest
    container_name: devops-project-1
    ports:
      - "80:8080"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
    restart: unless-stopped
    networks:
      - devops-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  devops-network:
    driver: bridge
